// DO NOT EDIT. This file is automatically generated.
//
// To re-generate, run:
//
//     scripts/autogen-builder-api <build-directory> [<compile-db>]

auto ctorUnit(ctor::unit::Fields fields, QualifiedTypePtr t, const Meta& meta = {}) {
    return spicy::ctor::Unit::create(context(), fields, t, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/ctors/unit.h:55:5
auto ctorUnit(ctor::unit::Fields fields, const Meta& meta = {}) {
    return spicy::ctor::Unit::create(context(), fields, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/ctors/unit.h:50:5
auto declarationHook(const hilti::declaration::Parameters& parameters, const StatementPtr& body, Engine engine,
                     AttributeSetPtr attrs, const Meta& m = Meta()) {
    return spicy::declaration::Hook::create(context(), parameters, body, engine, attrs, m);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/declarations/hook.h:82:5
auto declarationUnitHook(const ID& id, const declaration::HookPtr& hook, Meta meta = {}) {
    return spicy::declaration::UnitHook::create(context(), id, hook, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/declarations/unit-hook.h:21:5
auto statementConfirm(Meta meta = {}) {
    return spicy::statement::Confirm::create(context(), meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/statements/confirm.h:16:5
auto statementPrint(Expressions expressions, Meta meta = {}) {
    return spicy::statement::Print::create(context(), expressions, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/statements/print.h:19:5
auto statementReject(Meta meta = {}) {
    return spicy::statement::Reject::create(context(), meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/statements/reject.h:16:5
auto statementStop(Meta meta = {}) {
    return spicy::statement::Stop::create(context(), meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/statements/stop.h:16:5
auto typeSink(const Meta& meta = {}) {
    return spicy::type::Sink::create(context(), meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/sink.h:16:5
auto typeUnit(const hilti::declaration::Parameters& params, type::unit::Items items, AttributeSetPtr attrs,
              const Meta& meta = {}) {
    return spicy::type::Unit::create(context(), params, items, attrs, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit.h:104:5
auto typeUnit(hilti::type::Wildcard _, const Meta& meta = {}) {
    return spicy::type::Unit::create(context(), _, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit.h:117:5
auto typeUnitItemField(const ID& id, CtorPtr ctor, Engine engine, bool skip, Expressions args, ExpressionPtr repeat,
                       Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond, spicy::declaration::Hooks hooks,
                       const Meta& meta = {}) {
    return spicy::type::unit::item::Field::create(context(), id, ctor, engine, skip, args, repeat, sinks, attrs, cond,
                                                  hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/field.h:122:5
auto typeUnitItemField(const ID& id, const QualifiedTypePtr& type, Engine engine, bool skip, Expressions args,
                       ExpressionPtr repeat, Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond,
                       spicy::declaration::Hooks hooks, const Meta& meta = {}) {
    return spicy::type::unit::item::Field::create(context(), id, type, engine, skip, args, repeat, sinks, attrs, cond,
                                                  hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/field.h:115:5
auto typeUnitItemField(const ID& id, type::unit::ItemPtr item, Engine engine, bool skip, Expressions args,
                       ExpressionPtr repeat, Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond,
                       spicy::declaration::Hooks hooks, const Meta& meta = {}) {
    return spicy::type::unit::item::Field::create(context(), id, item, engine, skip, args, repeat, sinks, attrs, cond,
                                                  hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/field.h:129:5
auto typeUnitItemProperty(ID id, AttributeSetPtr attrs, bool inherited = false, const Meta& meta = {}) {
    return spicy::type::unit::item::Property::create(context(), id, attrs, inherited, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/property.h:31:5
auto typeUnitItemProperty(ID id, ExpressionPtr expr, AttributeSetPtr attrs, bool inherited = false,
                          const Meta& meta = {}) {
    return spicy::type::unit::item::Property::create(context(), id, expr, attrs, inherited, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/property.h:39:5
auto typeUnitItemSink(ID id, AttributeSetPtr attrs, const Meta& meta = {}) {
    return spicy::type::unit::item::Sink::create(context(), id, attrs, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/sink.h:29:5
auto typeUnitItemSwitch(ExpressionPtr expr, type::unit::item::switch_::Cases cases, Engine engine, ExpressionPtr cond,
                        spicy::declaration::Hooks hooks, AttributeSetPtr attrs, const Meta& meta = {}) {
    return spicy::type::unit::item::Switch::create(context(), expr, cases, engine, cond, hooks, attrs, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/switch.h:120:5
auto typeUnitItemSwitchCase(const Expressions& exprs, const type::unit::Items& items, const Meta& m = Meta()) {
    return spicy::type::unit::item::switch_::Case::create(context(), exprs, items, m);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/switch.h:53:5
auto typeUnitItemSwitchCase(const type::unit::ItemPtr& field, const Meta& m = Meta()) {
    return spicy::type::unit::item::switch_::Case::create(context(), field, m);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/switch.h:64:5
auto typeUnitItemSwitchCase(const type::unit::Items& items, const Meta& m = Meta()) {
    return spicy::type::unit::item::switch_::Case::create(context(), items, m);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/switch.h:59:5
auto typeUnitItemUnitHook(const ID& id, spicy::declaration::HookPtr hook, const Meta& meta = {}) {
    return spicy::type::unit::item::UnitHook::create(context(), id, hook, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/unit-hook.h:30:5
auto typeUnitItemUnresolvedField(ID id, CtorPtr ctor, Engine engine, bool skip, Expressions args, ExpressionPtr repeat,
                                 Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond,
                                 spicy::declaration::Hooks hooks, const Meta& meta = {}) {
    return spicy::type::unit::item::UnresolvedField::create(context(), id, ctor, engine, skip, args, repeat, sinks,
                                                            attrs, cond, hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/unresolved-field.h:67:5
auto typeUnitItemUnresolvedField(ID id, ID unresolved_id, Engine engine, bool skip, Expressions args,
                                 ExpressionPtr repeat, Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond,
                                 spicy::declaration::Hooks hooks, const Meta& meta = {}) {
    return spicy::type::unit::item::UnresolvedField::create(context(), id, unresolved_id, engine, skip, args, repeat,
                                                            sinks, attrs, cond, hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/unresolved-field.h:81:5
auto typeUnitItemUnresolvedField(ID id, QualifiedTypePtr type, Engine engine, bool skip, Expressions args,
                                 ExpressionPtr repeat, Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond,
                                 spicy::declaration::Hooks hooks, const Meta& meta = {}) {
    return spicy::type::unit::item::UnresolvedField::create(context(), id, type, engine, skip, args, repeat, sinks,
                                                            attrs, cond, hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/unresolved-field.h:60:5
auto typeUnitItemUnresolvedField(ID id, type::unit::ItemPtr item, Engine engine, bool skip, Expressions args,
                                 ExpressionPtr repeat, Expressions sinks, AttributeSetPtr attrs, ExpressionPtr cond,
                                 spicy::declaration::Hooks hooks, const Meta& meta = {}) {
    return spicy::type::unit::item::UnresolvedField::create(context(), id, item, engine, skip, args, repeat, sinks,
                                                            attrs, cond, hooks, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/unresolved-field.h:74:5
auto typeUnitItemVariable(ID id, QualifiedTypePtr type, ExpressionPtr default_, AttributeSetPtr attrs,
                          const Meta& meta = {}) {
    return spicy::type::unit::item::Variable::create(context(), id, type, default_, attrs, meta);
} // /Users/robin/work/spicy/node-rewrite/spicy/toolchain/include/spicy/ast/types/unit-items/variable.h:36:5
