# Copyright (c) 2020-now by the Zeek Project. See LICENSE for details.

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # vcpkg introduces a lot of churn but staying close
      # to upstream create diminishing ROI for us.
      - dependency-name: "3rdparty/vcpkg"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
