# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.

environment:
    CCACHE_BASEDIR: $CIRRUS_WORKING_DIR

    # Enforce sequential JIT'ing of files for controlled memory usage.
    HILTI_JIT_SEQUENTIAL: 1

    # Images for macOS
    IMAGE_MACOS_MONTEREY: ghcr.io/cirruslabs/macos-monterey-base:latest
    IMAGE_MACOS_VENTURA: ghcr.io/cirruslabs/macos-ventura-base:latest

    # Branches to use for spicy-plugin and spicy-analyzers tests.
    ZEEK_SPICY_BRANCH:      main
    ZEEK_ANALYZERS_BRANCH:  main

    # Cache HILTI C++ compilation.
    HILTI_CXX_COMPILER_LAUNCHER: ccache
    CCACHE_COMPRESS: "1"
    CCACHE_MAXSIZE: "2G"

ventura_task:
  skip: $CIRRUS_BRANCH != 'main' && $CIRRUS_TAG == ''
  macos_instance:
    image: $IMAGE_MACOS_VENTURA

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS
      reupload_on_changes: true

  env:
    CCACHE_DIR: /tmp/ccache

  update_git_script:
    - git submodule update --recursive --init
  install_dependencies_script:
    - brew install bison cmake flex ninja ccache
    - python3 -mvenv /tmp/btest.venv && /tmp/btest.venv/bin/pip install btest
  configure_script:
    - ./configure --with-flex=$(brew --prefix flex) --with-bison=$(brew --prefix bison) --generator=Ninja --enable-ccache --build-type=Debug
  build_script:
    - ninja -C build
  test_script:
    - (source /tmp/btest.venv/bin/activate && btest -djc tests/btest.cfg)
