# Copyright (c) 2020-now by the Zeek Project. See LICENSE for details.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: checkbashisms
    name: Check for bashisms in /bin/sh scripts
    entry: ./tests/Scripts/3rdparty/checkbashisms.pl
    language: script
    types: ["sh"]
    stages: ["pre-commit"]

  - id: license
    name: Check for license headers
    entry: ./tests/Scripts/license-header.py
    language: python
    stages: ["pre-commit"]
    types: [text]
    exclude: '^tests|NOTES|README|autogen|^(CHANGES|VERSION|scripts/ninja-build-stats|\.gitmodules|\.paths|.*\.(decl|json|rst|t2d|txt))$'

  - id: autogen-docs
    name: Check that generated documentation is up-to-date
    entry: ./doc/scripts/autogen-docs
    language: script
    pass_filenames: false
    stages: ["pre-commit"]

  - id: stray-baselines
    name: Check for stray BTest baselines
    entry: ./tests/Scripts/stray_baselines.py
    additional_dependencies:
      - btest
    language: python
    pass_filenames: false
    stages: ["pre-commit"]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 07a0f7667439f60724899f6ae288e4a4f572e0e1  # frozen: v22.1.2
  hooks:
  - id: clang-format
    types_or: ["c", "c++"]
    stages: ["pre-commit"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
    exclude: '^tests/Baseline'
  - id: end-of-file-fixer
    exclude: '^tests/Baseline|^doc/autogen|^doc/_static'
  - id: check-yaml
    stages: ["pre-commit"]
  - id: check-added-large-files

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 46cc8b337c73e5c1622ba0bb6dc21cdfcfe00c2f  # frozen: 0.8.0
  hooks:
  - id: cpplint
    exclude: '3rdparty/'
    args: ["--quiet"]
    stages: ["pre-commit"]

- repo: https://github.com/jorisroovers/gitlint
  rev:  acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
  hooks:
  - id: gitlint

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: rst-backticks
    stages: ["pre-commit"]
  - id: rst-directive-colons
    stages: ["pre-commit"]
  - id: rst-inline-touching-normal
    stages: ["pre-commit"]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: e2c2116d86a80e72e7146a06e68b7c228afc6319  # frozen: v0.6.13
  hooks:
  - id: cmake-format
    stages: ["pre-commit"]
  - id: cmake-lint
    stages: ["pre-commit"]

- repo: https://github.com/crate-ci/typos
  rev: 02ea592e44b3a53c302f697cddca7641cd051c3d  # frozen: v1.45.0
  hooks:
  - id: typos
    exclude: 'tests/.*/regexp/.*|.clang-tidy'

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: c60c980e561ed3e73101667fe8365c609d19a438  # frozen: v0.15.9
  hooks:
  - id: ruff-check
    args: [ --fix ]
  - id: ruff-format

exclude: 3rdparty/|doc/(autogen|.*examples)/|/Baseline/|(\.svg$)|(\.dat$)
