FROM ubuntu:eoan

ARG SKIP_BUILD=
ARG ZEEK_VERSION=3.0.11-0

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

CMD ["sh"]

ENV DEBIAN_FRONTEND=noninteractive
ENV CCACHE_DIR=/var/spool/ccache
ENV CCACHE_COMPRESS=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg2 \
 # Zeek.
 && mkdir -p /tmp/zeek-packages \
 && cd /tmp/zeek-packages \
 && curl -L --remote-name-all \
    https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/amd64/zeek-lts_${ZEEK_VERSION}_amd64.deb \
    https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/amd64/zeek-lts-core_${ZEEK_VERSION}_amd64.deb \
    https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/amd64/zeekctl-lts_${ZEEK_VERSION}_amd64.deb \
    https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/amd64/zeek-lts-core-dev_${ZEEK_VERSION}_amd64.deb \
    https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/amd64/libbroker-lts-dev_${ZEEK_VERSION}_amd64.deb \
    https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/amd64/zeek-lts-libcaf-dev_${ZEEK_VERSION}_amd64.deb \
 && apt-get install -y libpcap0.8 libpcap-dev python libssl-dev zlib1g-dev \
 && dpkg -i *.deb \
 && cd - \
 && rm -rf /tmp/zeek-packages \
 # Spicy build and test dependencies.
 && apt-get install -y --no-install-recommends git ninja-build ccache g++ llvm-9-dev clang-9 libclang-9-dev bison flex libfl-dev python3 python3-pip zlib1g-dev jq locales-all python3-setuptools python3-wheel \
 && pip3 install btest==0.64 pre-commit \
 # Spicy doc dependencies.
 && apt-get install -y --no-install-recommends python3-sphinx python3-sphinx-rtd-theme doxygen \
 # Cleanup.
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install a recent CMake.
WORKDIR /usr/local/cmake
RUN curl -L https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.tar.gz | tar xzvf - -C /usr/local/cmake --strip-components 1
ENV PATH="/usr/local/cmake/bin:${PATH}"

WORKDIR /root

# Install Spicy.
ADD . /opt/spicy/src
RUN test ! -z "${SKIP_BUILD}" || (cd /opt/spicy/src && ./configure --generator=Ninja --prefix=/opt/spicy --with-zeek=/opt/zeek && ninja -C build install && rm -rf build)
