#!/bin/bash
#
# Helper for the Makefile to trigger Docker commands with the desired image.

usage() {
    echo "usage: $(basename $0) build|test|run <platform>"
    exit 1
}

version=$(../scripts/autogen-version --short)
cmd=$1
platform=$2

if [ ! -e "Dockerfile.${platform}" ]; then
    echo "Dockerfile.${platform} does not exist"
    exit 1
fi

case "${cmd}" in
    build)
        test $# = 3 || usage
        DOCKER_BUILDKIT=1 docker build -t "spicy-base-${platform}:${version}" -f "Dockerfile.${platform}" .. || exit 1
        docker tag "$(docker inspect --format='{{.Id}}' "spicy-base-${platform}:${version}")" "spicy-${platform}:latest"
        IMG=spicy-build-$RANDOM
        docker run --name "${IMG}" -v "$(pwd)"/..:/spicy "spicy-base-${platform}:${version}" sh -c "git clone --recurse-submodules /spicy /opt/spicy/src && cd /opt/spicy/src && $3" || exit 1
        docker commit "${IMG}" "spicy-${platform}:${version}"
        docker commit ${IMG} "spicy-${platform}:latest"
        docker rm "${IMG}"
        ;;

    test)
        test $# = 2 || usage
        docker run "spicy-${platform}:latest" /bin/sh -c "cd /opt/spicy/src/tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -q -j -d"
        ;;

    run)
        test $# = 2 || usage
        docker run --cap-add SYS_PTRACE -i -t "spicy-${platform}:latest" /bin/bash
        ;;

    *) usage;;
esac
