FROM alpine:3.12

WORKDIR /root

RUN apk update

# Install development tools.
RUN apk add ccache cmake curl g++ gcc gdb git make ninja python3 vim linux-headers openssl-dev zlib-dev

# Install Spicy dependencies.
RUN apk add bash bison flex flex-dev flex-libs libucontext-dev py3-pip py3-sphinx py3-sphinx_rtd_theme doxygen
RUN pip3 install "btest>=0.66"

WORKDIR /root
