FROM ubuntu:eoan

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

CMD ["sh"]

ENV DEBIAN_FRONTEND=noninteractive
ENV CCACHE_DIR=/var/spool/ccache
ENV CCACHE_COMPRESS=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg2 \
 # Zeek.
 && echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/ /' > /etc/apt/sources.list.d/security:zeek.list \
 && curl https://download.opensuse.org/repositories/security:/zeek/xUbuntu_19.10/Release.key | apt-key add - \
 && apt-get update \
 && apt-get install -y --no-install-recommends zeek-lts zeek-lts-core-dev \
 # Spicy build and test dependencies.
 && apt-get install -y --no-install-recommends git ninja-build ccache g++ llvm-9-dev clang-9 libclang-9-dev bison flex libfl-dev python3 python3-pip zlib1g-dev jq locales-all python3-setuptools python3-wheel \
 && pip3 install btest pre-commit \
 # Spicy doc dependencies.
 && apt-get install -y --no-install-recommends python3-sphinx python3-sphinx-rtd-theme \
 # Cleanup.
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install a recent CMake.
WORKDIR /usr/local/cmake
RUN curl -L https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.tar.gz | tar xzvf - -C /usr/local/cmake --strip-components 1
ENV PATH="/usr/local/cmake/bin:${PATH}"

WORKDIR /root
