FROM fedora:33

RUN echo 'LC_CTYPE="C"' >> /etc/locale.conf \
 && echo 'LC_ALL="C"' >> /etc/locale.conf \
 && echo 'LANG="C"' >> /etc/locale.conf \
 # Install Spicy build dependencies
 && yum install -y ccache git ninja-build cmake flex bison gcc-c++ findutils diffutils python3-pip which openssl-devel zlib-devel \
 && pip3 install "btest>=0.66" \
 # Install rpmdevtools for packaging RPM files.
 && yum install -y rpmdevtools

WORKDIR /root
