# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.

FROM alpine:3.18

WORKDIR /root

RUN apk update

# Install development tools.
# We install diffutils instead of the builtin BusyBox `diff` to work around https://github.com/zeek/btest/issues/92.
RUN apk add ccache cmake curl diffutils g++ gcc gdb git make ninja python3 vim linux-headers openssl-dev zlib-dev

# Install Spicy dependencies.
RUN apk add bash bison flex flex-dev flex-libs libucontext-dev py3-pip py3-sphinx py3-sphinx_rtd_theme doxygen
RUN pip3 install "btest>=0.66"

WORKDIR /root
