// Copyright (c) 2023 by the Zeek Project. See LICENSE for details.

#include <hilti/ast/all.h>
#include <hilti/ast/operators/generic.h>
#include <hilti/ast/visitor-dispatcher.h>

using namespace hilti;

HILTI_NODE_IMPLEMENTATION_0(hilti, ASTRoot);
HILTI_NODE_IMPLEMENTATION_0(hilti, Attribute);
HILTI_NODE_IMPLEMENTATION_0(hilti, AttributeSet);
HILTI_NODE_IMPLEMENTATION_0(hilti, Ctor);
HILTI_NODE_IMPLEMENTATION_0(hilti, Declaration);
HILTI_NODE_IMPLEMENTATION_0(hilti, Expression);
HILTI_NODE_IMPLEMENTATION_0(hilti, Function);
HILTI_NODE_IMPLEMENTATION_0(hilti, QualifiedType);
HILTI_NODE_IMPLEMENTATION_0(hilti, Statement);
HILTI_NODE_IMPLEMENTATION_0(hilti, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_0(hilti, ctor::bitfield::BitRange);
HILTI_NODE_IMPLEMENTATION_0(hilti, ctor::map::Element)
HILTI_NODE_IMPLEMENTATION_0(hilti, ctor::struct_::Field);
HILTI_NODE_IMPLEMENTATION_0(hilti, statement::switch_::Case)
HILTI_NODE_IMPLEMENTATION_0(hilti, statement::try_::Catch)
HILTI_NODE_IMPLEMENTATION_0(hilti, type::bitfield::BitRange);
HILTI_NODE_IMPLEMENTATION_0(hilti, type::enum_::Label)
HILTI_NODE_IMPLEMENTATION_0(hilti, type::operand_list::Operand)
HILTI_NODE_IMPLEMENTATION_0(hilti, type::tuple::Element)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Address, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Bitfield, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Bool, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Bytes, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Coerced, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Default, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Enum, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Error, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Exception, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Interval, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Library, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::List, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Map, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Network, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Null, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Optional, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Port, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Real, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::RegExp, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Result, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Set, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::SignedInteger, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Stream, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::String, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::StrongReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Struct, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Time, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Tuple, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Union, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::UnsignedInteger, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::ValueReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Vector, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::WeakReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Constant, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Expression, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Field, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Function, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::GlobalVariable, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::ImportedModule, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::LocalVariable, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Module, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Parameter, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Property, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Type, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Assign, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::BuiltInFunction, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Coerced, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Ctor, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Deferred, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Grouping, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Keyword, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::ListComprehension, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::LogicalAnd, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::LogicalNot, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::LogicalOr, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Member, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Move, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Name, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::PendingCoerced, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Ternary, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::TypeInfo, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::TypeWrapped, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Type_, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::UnresolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Void, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, operator_::function::Call, ResolvedOperator)
HILTI_NODE_IMPLEMENTATION_1(hilti, operator_::generic::CastedCoercion, ResolvedOperator)
HILTI_NODE_IMPLEMENTATION_1(hilti, operator_::struct_::MemberCall, ResolvedOperator)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Assert, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Block, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Break, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Comment, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Continue, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Declaration, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Expression, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::For, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::If, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Return, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::SetLocation, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Switch, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Throw, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Try, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::While, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Yield, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Address, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Any, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Auto, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Bitfield, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Bool, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Bytes, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::DocOnly, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Enum, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Error, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Exception, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Function, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Interval, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Library, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::List, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Map, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Member, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Name, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Network, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Null, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::OperandList, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Optional, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Port, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Real, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::RegExp, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Result, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Set, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::SignedInteger, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Stream, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::String, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::StrongReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Struct, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Time, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Tuple, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Type_, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Union, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Unknown, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::UnsignedInteger, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::ValueReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Vector, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Void, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::WeakReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::bytes::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::list::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::map::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::set::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::stream::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::stream::View, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::vector::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::address::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::address::Family, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::address::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bitfield::HasMember, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bitfield::Member, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bool_::BitAnd, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bool_::BitOr, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bool_::BitXor, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bool_::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bool_::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::At, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Decode, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Find, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::In, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Join, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::LowerCase, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Match, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Split, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Split1, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::StartsWith, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Strip, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::SubIterator, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::SubIterators, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::SubOffsets, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::SumAssignBytes, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::SumAssignStreamView, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::SumAssignUInt8, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::ToIntAscii, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::ToIntBinary, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::ToTimeAscii, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::ToTimeBinary, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::ToUIntAscii, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::ToUIntBinary, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::UpperCase, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Difference, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::bytes::iterator::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::CastToSignedInteger, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::CastToUnsignedInteger, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::CtorSigned, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::CtorUnsigned, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::HasLabel, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::enum_::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::error::Ctor, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::error::Description, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::exception::Ctor, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::exception::Description, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::generic::Begin, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::generic::End, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::generic::New, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::generic::Pack, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::generic::Unpack, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::CtorRealSecs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::CtorSignedIntegerNs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::CtorSignedIntegerSecs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::CtorUnsignedIntegerNs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::CtorUnsignedIntegerSecs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Difference, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::MultipleReal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::MultipleUnsignedInteger, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Nanoseconds, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Seconds, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::interval::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::iterator::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::iterator::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::iterator::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::iterator::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::list::iterator::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::Clear, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::Delete, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::Get, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::In, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::IndexAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::IndexConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::IndexNonConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::iterator::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::iterator::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::iterator::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::iterator::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::map::iterator::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::network::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::network::Family, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::network::In, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::network::Length, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::network::Prefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::network::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::optional::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::port::Ctor, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::port::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::port::Protocol, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::port::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::CastToInterval, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::CastToSignedInteger, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::CastToTime, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::CastToUnsignedInteger, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Difference, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::DifferenceAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Division, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::DivisionAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Modulo, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Multiple, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::MultipleAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Power, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::SignNeg, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::real::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::regexp::Find, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::regexp::Match, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::regexp::MatchGroups, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::regexp::TokenMatcher, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::regexp_match_state::AdvanceBytes, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::regexp_match_state::AdvanceView, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::result::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::result::Error, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::Add, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::Clear, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::Delete, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::In, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::iterator::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::iterator::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::iterator::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::iterator::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::set::iterator::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CastToBool, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CastToEnum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CastToInterval, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CastToReal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CastToSigned, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CastToUnsigned, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorSigned16, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorSigned32, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorSigned64, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorSigned8, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorUnsigned16, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorUnsigned32, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorUnsigned64, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::CtorUnsigned8, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::DecrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::DecrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Difference, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::DifferenceAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Division, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::DivisionAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Modulo, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Multiple, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::MultipleAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Power, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::SignNeg, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::signed_integer::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::At, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::Ctor, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::Freeze, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::IsFrozen, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::SumAssignBytes, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::SumAssignView, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::Trim, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::Unfreeze, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Difference, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::IsFrozen, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Offset, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::iterator::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::AdvanceBy, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::AdvanceTo, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::AdvanceToNextData, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::At, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::EqualBytes, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::EqualView, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::Find, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::InBytes, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::InView, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::Limit, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::Offset, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::StartsWith, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::SubIterator, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::SubIterators, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::SubOffsets, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::UnequalBytes, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::stream::view::UnequalView, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::Encode, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::Modulo, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::string::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::strong_reference::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::strong_reference::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::strong_reference::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::struct_::HasMember, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::struct_::MemberConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::struct_::MemberNonConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::struct_::TryMember, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::struct_::Unset, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::CtorRealSecs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::CtorSignedIntegerNs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::CtorSignedIntegerSecs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::CtorUnsignedIntegerNs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::CtorUnsignedIntegerSecs, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::DifferenceInterval, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::DifferenceTime, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::Nanoseconds, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::Seconds, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::SumInterval, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::time::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::tuple::CustomAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::tuple::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::tuple::Index, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::tuple::Member, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::tuple::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::union_::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::union_::HasMember, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::union_::MemberConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::union_::MemberNonConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::union_::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::BitAnd, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::BitOr, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::BitXor, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToBool, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToEnum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToInterval, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToReal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToSigned, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToTime, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CastToUnsigned, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorSigned16, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorSigned32, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorSigned64, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorSigned8, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorUnsigned16, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorUnsigned32, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorUnsigned64, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::CtorUnsigned8, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::DecrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::DecrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Difference, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::DifferenceAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Division, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::DivisionAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Greater, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::GreaterEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Lower, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::LowerEqual, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Modulo, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Multiple, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::MultipleAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Negate, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Power, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::ShiftLeft, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::ShiftRight, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::SignNeg, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::unsigned_integer::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::value_reference::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::value_reference::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::value_reference::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Assign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::At, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Back, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Front, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::IndexConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::IndexNonConst, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::PopBack, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::PushBack, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Reserve, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Resize, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Size, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::SubEnd, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::SubRange, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Sum, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::SumAssign, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::iterator::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::iterator::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::iterator::IncrPostfix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::iterator::IncrPrefix, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::vector::iterator::Unequal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::weak_reference::Deref, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::weak_reference::Equal, ResolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_2(hilti, operator_::weak_reference::Unequal, ResolvedOperator, Expression)
