// Copyright (c) 2023 by the Zeek Project. See LICENSE for details.

#include <hilti/ast/all.h>
#include <hilti/ast/operators/generic.h>
#include <hilti/ast/visitor-dispatcher.h>

using namespace hilti;

HILTI_NODE_IMPLEMENTATION_0(hilti, ASTRoot);
HILTI_NODE_IMPLEMENTATION_0(hilti, Attribute);
HILTI_NODE_IMPLEMENTATION_0(hilti, AttributeSet);
HILTI_NODE_IMPLEMENTATION_0(hilti, Ctor);
HILTI_NODE_IMPLEMENTATION_0(hilti, Declaration);
HILTI_NODE_IMPLEMENTATION_0(hilti, Expression);
HILTI_NODE_IMPLEMENTATION_0(hilti, Function);
HILTI_NODE_IMPLEMENTATION_0(hilti, QualifiedType);
HILTI_NODE_IMPLEMENTATION_0(hilti, Statement);
HILTI_NODE_IMPLEMENTATION_0(hilti, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_0(hilti, ctor::bitfield::BitRange);
HILTI_NODE_IMPLEMENTATION_0(hilti, ctor::map::Element)
HILTI_NODE_IMPLEMENTATION_0(hilti, ctor::struct_::Field);
HILTI_NODE_IMPLEMENTATION_0(hilti, statement::switch_::Case)
HILTI_NODE_IMPLEMENTATION_0(hilti, statement::try_::Catch)
HILTI_NODE_IMPLEMENTATION_0(hilti, type::bitfield::BitRange);
HILTI_NODE_IMPLEMENTATION_0(hilti, type::enum_::Label)
HILTI_NODE_IMPLEMENTATION_0(hilti, type::operand_list::Operand)
HILTI_NODE_IMPLEMENTATION_0(hilti, type::tuple::Element)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Address, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Bitfield, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Bool, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Bytes, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Coerced, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Default, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Enum, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Error, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Exception, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Interval, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Library, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::List, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Map, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Network, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Null, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Optional, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Port, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Real, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::RegExp, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Result, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Set, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::SignedInteger, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Stream, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::String, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::StrongReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Struct, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Time, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Tuple, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Union, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::UnsignedInteger, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::ValueReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::Vector, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, ctor::WeakReference, Ctor)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Constant, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Expression, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Field, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Function, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::GlobalVariable, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::ImportedModule, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::LocalVariable, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Module, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Parameter, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Property, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, declaration::Type, Declaration)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Assign, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::BuiltInFunction, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Coerced, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Ctor, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Deferred, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Grouping, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Keyword, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::ListComprehension, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::LogicalAnd, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::LogicalNot, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::LogicalOr, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Member, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Move, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Name, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::PendingCoerced, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Ternary, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::TypeInfo, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::TypeWrapped, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Type_, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::UnresolvedOperator, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, expression::Void, Expression)
HILTI_NODE_IMPLEMENTATION_1(hilti, operator_::function::Call, ResolvedOperator)
HILTI_NODE_IMPLEMENTATION_1(hilti, operator_::generic::CastedCoercion, ResolvedOperator)
HILTI_NODE_IMPLEMENTATION_1(hilti, operator_::struct_::MemberCall, ResolvedOperator)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Assert, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Block, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Break, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Comment, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Continue, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Declaration, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Expression, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::For, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::If, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Return, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::SetLocation, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Switch, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Throw, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Try, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::While, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, statement::Yield, Statement)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Address, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Any, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Auto, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Bitfield, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Bool, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Bytes, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::DocOnly, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Enum, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Error, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Exception, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Function, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Interval, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Library, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::List, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Map, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Member, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Name, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Network, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Null, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::OperandList, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Optional, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Port, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Real, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::RegExp, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Result, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Set, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::SignedInteger, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Stream, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::String, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::StrongReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Struct, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Time, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Tuple, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Type_, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Union, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Unknown, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::UnsignedInteger, UnqualifiedType);
HILTI_NODE_IMPLEMENTATION_1(hilti, type::ValueReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Vector, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::Void, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::WeakReference, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::bytes::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::list::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::map::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::set::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::stream::Iterator, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::stream::View, UnqualifiedType)
HILTI_NODE_IMPLEMENTATION_1(hilti, type::vector::Iterator, UnqualifiedType)
