#!/bin/sh

# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.

if [ $# != 1 ]; then
    echo "usage: $(basename $0) <cxx-path>"
    exit 1
fi

$1 -### 2>&1 | grep ^InstalledDir | cut -d ' ' -f 2
