#! /usr/bin/env bash
#
# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.

base=$(cd $(dirname $0); pwd)

pcpp  --passthru-unfound-includes ${base}/expand-old-operators.h $@ | \
    gsed -E 's/type::([a-z])([A-Za-z_]*)::([A-Z][A-Za-z]*)\(/builder->type\U\1\E\2\3(/g' | \
    gsed -E 's/type::([A-Z][A-Za-z_]*)\(/builder->type\1(/g' | \
    gsed -E 's/builder->typeWildcard\(\)/type::Wildcard()/g' | \
    gsed -E 's/type::constant\(([^,]*)\)\}/\1}/g' | \
    gsed -E 's/builder->type([a-wyz])/builder->type\U\1\E/g' | \
    gsed -E 's/.member = "([A-Z])/.member = "\L\1\E/g' | \
    gsed -E 's/builder::id\(/builder->expressionName(/g' | \
    egrep -v 'namespace|#line' | \
    clang-format | \
    gsed -E 's/.*@ @\*;/#if 0/g' | \
    gsed -E 's/.*@ @\^;/#endif/g' | \
    gsed -E 's/^\)"\};/)",/g' | \
    gsed -E 's/_"/"/g' | \
    gsed -E 's/ops/operands/g' | \
    egrep -v 'return _signature;' | \
    gsed -E 's/builder->typeEnum\(type::Wildcard\(\)\)/builder->typeName("hilti::xx")/g' | \
    awk '/HILTI_OPERATOR\(/ {print ""} {print}' | \
    cat


#awk '/@ @ @ @/ { indent = 1 - indent; print "------"; next } indent == 1 { printf "        "; } { print; }' | \
