#! /usr/bin/env bash
#
# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.

if [ $# != 1 ]; then
    echo "Usage: $0 <file.cc>"
    exit 1
fi

cc=$1

cat ${cc} | gawk '
    BEGIN { print "---"; c1 = 0; c2 = 0; }
    c1 == 0 && c2 == 0 && match($0, /^(.*void operator\(\)\([^ ]* )([^)]*)\)/, m) {
        print "- Offset:", offset + length(m[1]) + 1;
        print "  NewName: n"
    }

    /#if *0/ { c1 += 1; }
    /#endif/ { c1 -= 1; }

    c1 == 0 && /\/\*/ { c2 = 1; }
    c2 == 1 && /\*\// { c2 = 0; }

    { offset += length($0) + 1; }
' >${cc}.yaml

cat ${cc}.yaml

clang-rename --force -input=${cc}.yaml ${cc} >${cc}.new && mv ${cc}.new ${cc}

rm -f ${cc}.yaml
