### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
        std::string Xstd{};
        // std::string Xopt{};
            return "["s + "$Xstd=" + hilti::rt::to_string(Xstd) + ", "s + hilti::rt::to_string_for_print("$Xopt=(optimized out)") + "]";
    const ::hilti::rt::TypeInfo _t_ti_Test__Foo_namex2aTest__Foox2b = { "Test::Foo", "Test::Foo", [](const void *self) { return hilti::rt::to_string(*reinterpret_cast<const hlt_internal::Test::Foo*>(self)); }, new ::hilti::rt::type_info::Struct(std::vector<::hilti::rt::type_info::struct_::Field>({::hilti::rt::type_info::struct_::Field{ "Xstd", &::hilti::rt::type_info::string, static_cast<std::ptrdiff_t>(offsetof(Test::Foo, Xstd)), false, false, true }, ::hilti::rt::type_info::struct_::Field{ "Xopt", &::hilti::rt::type_info::string, std::ptrdiff_t{-1}, false, false, false }})) };
