# Copyright (c) 2020-now by the Zeek Project. See LICENSE for details.

name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl ca-certificates gnupg2
          sudo apt-get install -y --no-install-recommends \
              bison \
              ccache \
              flex \
              g++ \
              libfl-dev \
              libssl-dev \
              make \
              ninja-build \
              zlib1g-dev

      - name: ccache
        uses: hendrikmuhs/ccache-action@f09c25b45002a07be2955cbe52e8cee55643f89d
        with:
          create-symlink: true
          key: ${{ github.job }}

      - name: Build benchmarks
        env:
          HILTI_OPTIMIZER_ENABLE_CFG: 1
        run: |
          cmake -G Ninja -DCODSPEED_MODE=instrumentation -DCMAKE_BUILD_TYPE=RelWithDebInfo -Bbuild /spicy
          ninja -C build spicy-rt-parsing-benchmark hilti-rt-benchmark

      - uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8
        with:
          run: |
            ./build/bin/hilti-rt-benchmark
            ./build/bin/spicy-rt-parsing-benchmark
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: simulation
