#! /bin/sh
# shellcheck disable=SC2086

# shellcheck source=tests/Scripts/cxx-common.sh
. "$(dirname "$0")"/cxx-common.sh

cxx=$(spicy-config --cxx)
ldflags=$(spicy-config --ldflags ${debug})

exec "${cxx}" "$@" ${ldflags}
