#! /bin/sh

# FIXME(bbannier): let's not add this and instead fix the compiler to do the right thing on windows. If we can do that we can also roll back many test modifications.

. $(dirname $0)/cxx-common.sh

cxx="$(spicy-config --cxx)"
cxxflags="$(spicy-config --cxxflags-hlto ${debug})"
ldflags="$(spicy-config --ldflags-hlto ${debug})"

if cxx_is_msvc "$cxx"; then
    # MSVC DLLs require all symbols resolved at link time, so include
    # the runtime import libraries alongside the HLTO-specific flags.
    rtlibs="$(hilti-config --ldflags ${debug}) $(spicy-config --ldflags ${debug})"
    msvc_parse_args "$@"
    "${cxx}" ${cxxflags} ${ldflags} ${MSVC_ARGS} "/Fe:${MSVC_OUT:-a.hlto}" /link ${rtlibs}
else
    exec "${cxx}" ${cxxflags} $@ ${ldflags}
fi
