#! /bin/sh
#
# Returns success if we have Zeek's Spicy plugin (and Zeek itself) available for testing.
# Optionally it also requires at least Zeek version $1.

min_version=0
test $# -ge 1 && min_version=$1

spicy-config --zeek-plugin-path >/dev/null && \
    test "$(spicy-config --zeek-version-number)" -ge "${min_version}"
