#! /bin/sh
#
# Returns success if we have Zeek's Spicy plugin available in tree for testing.

base=$(cd $(dirname $0) && pwd)

if [ -n "${SPICY_INSTALLATION_DIRECTORY}" ]; then
     test -x ${SPICY_INSTALLATION_DIRECTORY}/bin/spicyz
else
    cat $(${base}/build-directory)/CMakeCache.txt | egrep -iq 'HAVE_ZEEK_PLUGIN.*=(yes|on|true)'
fi
