#! /bin/sh
#
# Returns success if we have comnpiled the Zeek plugin (1) at all, and (2) with with JIT suport.
# Optionally it also requires at least Zeek version $1.

min_version=0
test $# -ge 1 && min_version=$1

spicy-config --zeek-plugin-path >/dev/null && \
    test "$(spicy-config --zeek-version)" -ge "${min_version}" && \
    test "$(spicy-config --zeek-jit-support)" == "yes"
