### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
    inline auto to_string(hlt_internal::Test::E x, adl::tag) -> std::string;
inline auto ::hilti::rt::detail::adl::to_string(hlt_internal::Test::E x, adl::tag) -> std::string {
